### ISSUE TITLE
Does not work on 64 bit windows

### ISSUE THREAD

**Issue by AffectedArc07** [qwertyquerty/ss13rp#1]
![image](https://user-images.githubusercontent.com/25063394/39533078-1ae4d9be-4e26-11e8-8f22-6c78dabe3a2d.png)

**Comment by AffectedArc07** [comment]
Reinstall fixed it

**Comment by qwertyquerty** [comment]
Hmmm, ok. Not sure why this happened in the first place... I've updated the installer since then, but nothing that should have fixed something like that
